# Generated by Django 2.1.7 on 2020-11-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
