# Generated by Django 2.1.7 on 2020-11-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('type_of_pet', models.CharField(max_length=100)),
                ('food_cost', models.IntegerField(default=0)),
                ('image', models.FileField(upload_to='')),
                ('food_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('food_update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'Food',
            },
        ),
    ]
