# Generated by Django 2.1.7 on 2020-11-26 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_creation',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_update',
        ),
    ]
